# Change these first
owner: mossgrid # Your GitHub organization or username, where this repository lives
repo: sentinel # The name of this repository

sites:
  - name: buymezobo
    url: https://buymezobo.ng
  - name: buymezobo dev
    url: https://buymezobo.vercel.app/
  - name: api.buymezobo
    url: https://core.buymezobo.ng/api/healthcheck

  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  baseUrl: /sentinel
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://mossgrid.netlify.app/mg.png
  name: sentinel
  theme: light
  introTitle: "**Sentinel**"
  introMessage: status page for mossgrid services. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
