# Change these first
owner: mossgrid # Your GitHub organization or username, where this repository lives
repo: sentinel # The name of this repository

sites:
  - name: buymezobo dev
    url: https://buymezobo.vercel.app/
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  baseUrl: /sentinel
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://mossgrid.netlify.app/mg.png
  name: sentinel
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introTitle: "**Sentinel**: status page for Mossgrid services"
  introMessage: we're a group of friends on a mission to empower Nigeria through technology. At MossGrid, we're building both open-source and profit-driven software that addresses Nigeria's unique needs. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
